
volumes:
  data:

services:
  init:
    #image: ubuntu:latest
    build:
      context: ./
      dockerfile: Dockerfile-init
    #command: chown 1002:1002 -R /data
    volumes:
      - data:/data
  app:
    #image: ubuntu:latest
    build:
      context: ./
    depends_on:
      - init
    #command: tail -f /dev/null
    volumes:
      - data:/data
